version: '3.3'

services:
  shinyproxy:
    image: ghcr.io/matteofasulo/shinyproxy:2.6.1
    ports:
      - 8020
    networks:
      - traefik-public
      - sp-net
    environment:
      - AUTH_URL=${AUTH_URL}
      - LOGOUT_URL=${LOGOUT_URL}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - EMAIL=${EMAIL}
      - SMTP_MAIL_USER=${SMTP_MAIL_USER}
      - SMTP_MAIL_PASSWORD=${SMTP_MAIL_PASSWORD}
      - SMTP_MAIL_HOST=${SMTP_MAIL_HOST}
      - TOKEN_URL=${TOKEN_URL}
      - JWKS_URL=${JWKS_URL}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role==manager
      labels:
          - traefik.enable=true # enable traefik
          - traefik.docker.network=traefik-public # put it in the same network as traefik
          - traefik.constraint-label=traefik-public # assign the same label as traefik so it can be discovered
          - traefik.http.routers.shinyproxy.rule=Host(`${APP_DOMAIN?Variable not set}`) # listen to port 80 for request to APP_DOMAIN (use together with the line below)
          - traefik.http.routers.shinyproxy.entrypoints=http
          - traefik.http.middlewares.shinyproxy.redirectscheme.scheme=https # redirect traffic to https
          - traefik.http.middlewares.shinyproxy.redirectscheme.permanent=true # redirect traffic to https
          - traefik.http.routers.shinyproxy-secured.rule=Host(`${APP_DOMAIN?Variable not set}`) # listen to port 443 for request to APP_DOMAIN (use together with the line below)
          - traefik.http.routers.shinyproxy-secured.entrypoints=https
          - traefik.http.middlewares.hsts-headers.headers.sslRedirect=true
          - traefik.http.middlewares.hsts-headers.headers.forceSTSHeader=true
          - traefik.http.routers.shinyproxy-secured.tls=true
          - traefik.http.routers.shinyproxy-secured.tls.certresolver=le # use the Let's Encrypt certificate we set up earlier
          - traefik.http.services.shinyproxy-secured.loadbalancer.server.port=8020 # ask Traefik to search for port 8080 of the shinyproxy service container
    volumes:
      - ./application/application.yml:/opt/shinyproxy/application.yml
      - /var/run/docker.sock:/var/run/docker.sock

  #dashboard:
  #  image: sp.batgames.it:5000/matteofasulo/amazon-dashboard:latest
  #  networks:
  #    - sp-net

networks:
  traefik-public:
    external: true
  sp-net:
    external: true
